# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  matrix:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.set-matrix.outputs.matrix }} 
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - id: set-matrix
      # Runs a set of commands using the runners shell
      # - name: Run a multi-line script
        run: |
          sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
          sudo chmod a+x /usr/local/bin/yq
          yq --version
          declare -a array=$(yq '.biapps' config.yaml)
          echo $array
          declare -a newarr=$(echo ${array[@]//:/ })
          echo $newarr
          declare -a testarr=$(echo ${newarr[*]// /,})
          echo $testarr
          #Final Array 'a'
          a=($(echo "$testarr" | tr ',' '\n'))
          echo "the array 'a' contains ${#a[@]} elements"
          echo "Final Array is a = [ ${a[*]} ] "
          jobs=(${a[*]})
          echo "::set-output name=matrix::$(${a[*]})"
  job2:
    runs-on: ubuntu-latest
    needs: [matrix]
    steps:
      - run: echo ${{needs.matrix.outputs.output1}}

