name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  
  job1:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{steps.step1.outputs.test}} 
    steps:
      - uses: actions/checkout@v3
      - id: step1
        run: |
          sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
          sudo chmod a+x /usr/local/bin/yq
          sudo apt install -y jq
          declare -a array=$(yq '.biapps' config.yaml)
          declare -a newarr=$(echo ${array[@]//:/ })
          declare -a testarr=$(echo ${newarr[*]// /,})
          a=($(echo "$testarr" | tr ',' '\n'))
          b=$(jq --compact-output --null-input '$ARGS.positional' --args -- "${a[@]}")
          echo "::set-output name=test::$b"

  job2:
    needs: [job1]
    strategy:
      fail-fast: false
      matrix:
        input: ${{fromJSON(needs.job1.outputs.output1)}}
    
    runs-on: ubuntu-latest
    steps:
      
      - run: echo ${{needs.job1.outputs.output1}} && echo ${{ matrix.input }}

